# runs the buildout and tests onegov.org, because that's the package with
# the most dependencies and number of tests
language: python
python: "3.5"

env:
    - ES_VERSION=5.5.2

addons:
    postgresql: "9.3"

install: ./.travis.sh

script: py.test src/onegov.org
