# runs the buildout and tests onegov.org, because that's the package with
# the most dependencies and number of tests
language: python
python: "3.6"

# required for google chrome
dist: trusty

env:
    - ES_VERSION=5.5.2

addons:
    postgresql: "9.6"
    apt:
        packages:
            - oracle-java8-set-default
            - google-chrome-stable
            - ghostscript

install: ./.travis.sh

script: py.test src/onegov.org
