# runs the buildout and tests onegov.org, because that's the package with
# the most dependencies and number of tests
language: python
python: "3.4"

env:
    - TOXENV=py34 ES_BINARY=/tmp/elasticsearch/bin/elasticsearch ES_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.5.0.tar.gz

addons:
    postgresql: "9.3"

install: ./.travis.sh

script: py.test src/onegov.org
