# runs the buildout and tests onegov.org, because that's the package with
# the most dependencies and number of tests
language: python
python: "3.6"
dist: xenial

env:
    - ES_VERSION=5.5.2

addons:
    postgresql: "9.6"
    chrome: stable
    apt:
        packages:
            - openjdk-8-jre-headless
            - ghostscript
            - libpoppler-cpp-dev
            - libgnutls28-dev
            - libev-dev

script: make install
